# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from CREModel.app.protos import relation_pb2 as relation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in relation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictRelation = channel.unary_unary(
                '/protos.RelationService/PredictRelation',
                request_serializer=relation__pb2.PredictRequest.SerializeToString,
                response_deserializer=relation__pb2.PredictResponse.FromString,
                _registered_method=True)


class RelationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictRelation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictRelation': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictRelation,
                    request_deserializer=relation__pb2.PredictRequest.FromString,
                    response_serializer=relation__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.RelationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.RelationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictRelation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.RelationService/PredictRelation',
            relation__pb2.PredictRequest.SerializeToString,
            relation__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
