# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erelation.proto\x12\x06protos\"D\n\x0ePredictRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0f\n\x07\x65ntity1\x18\x02 \x01(\t\x12\x0f\n\x07\x65ntity2\x18\x03 \x01(\t\"F\n\x0fPredictResponse\x12\x10\n\x08relation\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05\x65rror\x18\x03 \x01(\t2W\n\x0fRelationService\x12\x44\n\x0fPredictRelation\x12\x16.protos.PredictRequest\x1a\x17.protos.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=26
  _globals['_PREDICTREQUEST']._serialized_end=94
  _globals['_PREDICTRESPONSE']._serialized_start=96
  _globals['_PREDICTRESPONSE']._serialized_end=166
  _globals['_RELATIONSERVICE']._serialized_start=168
  _globals['_RELATIONSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
