// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: relation.proto

#include "relation.pb.h"
#include "relation.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace protos {

static const char* RelationService_method_names[] = {
  "/protos.RelationService/PredictRelation",
};

std::unique_ptr< RelationService::Stub> RelationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RelationService::Stub> stub(new RelationService::Stub(channel, options));
  return stub;
}

RelationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PredictRelation_(RelationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RelationService::Stub::PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::protos::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protos::PredictRequest, ::protos::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PredictRelation_, context, request, response);
}

void RelationService::Stub::async::PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protos::PredictRequest, ::protos::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PredictRelation_, context, request, response, std::move(f));
}

void RelationService::Stub::async::PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PredictRelation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>* RelationService::Stub::PrepareAsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protos::PredictResponse, ::protos::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PredictRelation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>* RelationService::Stub::AsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRelationRaw(context, request, cq);
  result->StartCall();
  return result;
}

RelationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RelationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RelationService::Service, ::protos::PredictRequest, ::protos::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RelationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protos::PredictRequest* req,
             ::protos::PredictResponse* resp) {
               return service->PredictRelation(ctx, req, resp);
             }, this)));
}

RelationService::Service::~Service() {
}

::grpc::Status RelationService::Service::PredictRelation(::grpc::ServerContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protos

