// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relation.proto
// Protobuf C++ Version: 5.29.3

#include "relation.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protos {

inline constexpr PredictResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : relation_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        confidence_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PredictResponse::PredictResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PredictResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PredictResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PredictResponseDefaultTypeInternal() {}
  union {
    PredictResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PredictResponseDefaultTypeInternal _PredictResponse_default_instance_;

inline constexpr PredictRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sentence_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entity1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entity2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PredictRequest::PredictRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PredictRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PredictRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PredictRequestDefaultTypeInternal() {}
  union {
    PredictRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PredictRequestDefaultTypeInternal _PredictRequest_default_instance_;
}  // namespace protos
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_relation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_relation_2eproto = nullptr;
const ::uint32_t
    TableStruct_relation_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protos::PredictRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protos::PredictRequest, _impl_.sentence_),
        PROTOBUF_FIELD_OFFSET(::protos::PredictRequest, _impl_.entity1_),
        PROTOBUF_FIELD_OFFSET(::protos::PredictRequest, _impl_.entity2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protos::PredictResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protos::PredictResponse, _impl_.relation_),
        PROTOBUF_FIELD_OFFSET(::protos::PredictResponse, _impl_.confidence_),
        PROTOBUF_FIELD_OFFSET(::protos::PredictResponse, _impl_.error_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protos::PredictRequest)},
        {11, -1, -1, sizeof(::protos::PredictResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protos::_PredictRequest_default_instance_._instance,
    &::protos::_PredictResponse_default_instance_._instance,
};
const char descriptor_table_protodef_relation_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016relation.proto\022\006protos\"D\n\016PredictReque"
    "st\022\020\n\010sentence\030\001 \001(\t\022\017\n\007entity1\030\002 \001(\t\022\017\n"
    "\007entity2\030\003 \001(\t\"F\n\017PredictResponse\022\020\n\010rel"
    "ation\030\001 \001(\t\022\022\n\nconfidence\030\002 \001(\002\022\r\n\005error"
    "\030\003 \001(\t2W\n\017RelationService\022D\n\017PredictRela"
    "tion\022\026.protos.PredictRequest\032\027.protos.Pr"
    "edictResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_relation_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_relation_2eproto = {
    false,
    false,
    263,
    descriptor_table_protodef_relation_2eproto,
    "relation.proto",
    &descriptor_table_relation_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_relation_2eproto::offsets,
    file_level_enum_descriptors_relation_2eproto,
    file_level_service_descriptors_relation_2eproto,
};
namespace protos {
// ===================================================================

class PredictRequest::_Internal {
 public:
};

PredictRequest::PredictRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protos.PredictRequest)
}
inline PROTOBUF_NDEBUG_INLINE PredictRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protos::PredictRequest& from_msg)
      : sentence_(arena, from.sentence_),
        entity1_(arena, from.entity1_),
        entity2_(arena, from.entity2_),
        _cached_size_{0} {}

PredictRequest::PredictRequest(
    ::google::protobuf::Arena* arena,
    const PredictRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PredictRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:protos.PredictRequest)
}
inline PROTOBUF_NDEBUG_INLINE PredictRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sentence_(arena),
        entity1_(arena),
        entity2_(arena),
        _cached_size_{0} {}

inline void PredictRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PredictRequest::~PredictRequest() {
  // @@protoc_insertion_point(destructor:protos.PredictRequest)
  SharedDtor(*this);
}
inline void PredictRequest::SharedDtor(MessageLite& self) {
  PredictRequest& this_ = static_cast<PredictRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sentence_.Destroy();
  this_._impl_.entity1_.Destroy();
  this_._impl_.entity2_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PredictRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PredictRequest(arena);
}
constexpr auto PredictRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PredictRequest),
                                            alignof(PredictRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PredictRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PredictRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PredictRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PredictRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PredictRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PredictRequest>(), &PredictRequest::ByteSizeLong,
            &PredictRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_._cached_size_),
        false,
    },
    &PredictRequest::kDescriptorMethods,
    &descriptor_table_relation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PredictRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 52, 2> PredictRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protos::PredictRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string sentence = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.sentence_)}},
    // string entity1 = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.entity1_)}},
    // string entity2 = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.entity2_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sentence = 1;
    {PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.sentence_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string entity1 = 2;
    {PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.entity1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string entity2 = 3;
    {PROTOBUF_FIELD_OFFSET(PredictRequest, _impl_.entity2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\10\7\7\0\0\0\0"
    "protos.PredictRequest"
    "sentence"
    "entity1"
    "entity2"
  }},
};

PROTOBUF_NOINLINE void PredictRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.PredictRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sentence_.ClearToEmpty();
  _impl_.entity1_.ClearToEmpty();
  _impl_.entity2_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PredictRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PredictRequest& this_ = static_cast<const PredictRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PredictRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PredictRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protos.PredictRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string sentence = 1;
          if (!this_._internal_sentence().empty()) {
            const std::string& _s = this_._internal_sentence();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protos.PredictRequest.sentence");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string entity1 = 2;
          if (!this_._internal_entity1().empty()) {
            const std::string& _s = this_._internal_entity1();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protos.PredictRequest.entity1");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string entity2 = 3;
          if (!this_._internal_entity2().empty()) {
            const std::string& _s = this_._internal_entity2();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protos.PredictRequest.entity2");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protos.PredictRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PredictRequest::ByteSizeLong(const MessageLite& base) {
          const PredictRequest& this_ = static_cast<const PredictRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PredictRequest::ByteSizeLong() const {
          const PredictRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protos.PredictRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string sentence = 1;
            if (!this_._internal_sentence().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sentence());
            }
            // string entity1 = 2;
            if (!this_._internal_entity1().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_entity1());
            }
            // string entity2 = 3;
            if (!this_._internal_entity2().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_entity2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PredictRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PredictRequest*>(&to_msg);
  auto& from = static_cast<const PredictRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protos.PredictRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sentence().empty()) {
    _this->_internal_set_sentence(from._internal_sentence());
  }
  if (!from._internal_entity1().empty()) {
    _this->_internal_set_entity1(from._internal_entity1());
  }
  if (!from._internal_entity2().empty()) {
    _this->_internal_set_entity2(from._internal_entity2());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PredictRequest::CopyFrom(const PredictRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.PredictRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PredictRequest::InternalSwap(PredictRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sentence_, &other->_impl_.sentence_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.entity1_, &other->_impl_.entity1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.entity2_, &other->_impl_.entity2_, arena);
}

::google::protobuf::Metadata PredictRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PredictResponse::_Internal {
 public:
};

PredictResponse::PredictResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protos.PredictResponse)
}
inline PROTOBUF_NDEBUG_INLINE PredictResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protos::PredictResponse& from_msg)
      : relation_(arena, from.relation_),
        error_(arena, from.error_),
        _cached_size_{0} {}

PredictResponse::PredictResponse(
    ::google::protobuf::Arena* arena,
    const PredictResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PredictResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.confidence_ = from._impl_.confidence_;

  // @@protoc_insertion_point(copy_constructor:protos.PredictResponse)
}
inline PROTOBUF_NDEBUG_INLINE PredictResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : relation_(arena),
        error_(arena),
        _cached_size_{0} {}

inline void PredictResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.confidence_ = {};
}
PredictResponse::~PredictResponse() {
  // @@protoc_insertion_point(destructor:protos.PredictResponse)
  SharedDtor(*this);
}
inline void PredictResponse::SharedDtor(MessageLite& self) {
  PredictResponse& this_ = static_cast<PredictResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.relation_.Destroy();
  this_._impl_.error_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PredictResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PredictResponse(arena);
}
constexpr auto PredictResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PredictResponse),
                                            alignof(PredictResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PredictResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PredictResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PredictResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PredictResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PredictResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PredictResponse>(), &PredictResponse::ByteSizeLong,
            &PredictResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_._cached_size_),
        false,
    },
    &PredictResponse::kDescriptorMethods,
    &descriptor_table_relation_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PredictResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 44, 2> PredictResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protos::PredictResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string relation = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.relation_)}},
    // float confidence = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.confidence_)}},
    // string error = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.error_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string relation = 1;
    {PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.relation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float confidence = 2;
    {PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.confidence_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // string error = 3;
    {PROTOBUF_FIELD_OFFSET(PredictResponse, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\10\0\5\0\0\0\0"
    "protos.PredictResponse"
    "relation"
    "error"
  }},
};

PROTOBUF_NOINLINE void PredictResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protos.PredictResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.relation_.ClearToEmpty();
  _impl_.error_.ClearToEmpty();
  _impl_.confidence_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PredictResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PredictResponse& this_ = static_cast<const PredictResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PredictResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PredictResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protos.PredictResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string relation = 1;
          if (!this_._internal_relation().empty()) {
            const std::string& _s = this_._internal_relation();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protos.PredictResponse.relation");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // float confidence = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_confidence(), target);
          }

          // string error = 3;
          if (!this_._internal_error().empty()) {
            const std::string& _s = this_._internal_error();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protos.PredictResponse.error");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protos.PredictResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PredictResponse::ByteSizeLong(const MessageLite& base) {
          const PredictResponse& this_ = static_cast<const PredictResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PredictResponse::ByteSizeLong() const {
          const PredictResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protos.PredictResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string relation = 1;
            if (!this_._internal_relation().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_relation());
            }
            // string error = 3;
            if (!this_._internal_error().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error());
            }
            // float confidence = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_confidence()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PredictResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PredictResponse*>(&to_msg);
  auto& from = static_cast<const PredictResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protos.PredictResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_relation().empty()) {
    _this->_internal_set_relation(from._internal_relation());
  }
  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_confidence()) != 0) {
    _this->_impl_.confidence_ = from._impl_.confidence_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PredictResponse::CopyFrom(const PredictResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protos.PredictResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PredictResponse::InternalSwap(PredictResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.relation_, &other->_impl_.relation_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
        swap(_impl_.confidence_, other->_impl_.confidence_);
}

::google::protobuf::Metadata PredictResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_relation_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
