// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: relation.proto
#ifndef GRPC_relation_2eproto__INCLUDED
#define GRPC_relation_2eproto__INCLUDED

#include "relation.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace protos {

class RelationService final {
 public:
  static constexpr char const* service_full_name() {
    return "protos.RelationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::protos::PredictResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>> AsyncPredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>>(AsyncPredictRelationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>> PrepareAsyncPredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>>(PrepareAsyncPredictRelationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>* AsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::protos::PredictResponse>* PrepareAsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::protos::PredictResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>> AsyncPredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>>(AsyncPredictRelationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>> PrepareAsyncPredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>>(PrepareAsyncPredictRelationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, std::function<void(::grpc::Status)>) override;
      void PredictRelation(::grpc::ClientContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>* AsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::protos::PredictResponse>* PrepareAsyncPredictRelationRaw(::grpc::ClientContext* context, const ::protos::PredictRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PredictRelation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PredictRelation(::grpc::ServerContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PredictRelation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredictRelation(::grpc::ServerContext* context, ::protos::PredictRequest* request, ::grpc::ServerAsyncResponseWriter< ::protos::PredictResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PredictRelation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PredictRelation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::protos::PredictRequest, ::protos::PredictResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::protos::PredictRequest* request, ::protos::PredictResponse* response) { return this->PredictRelation(context, request, response); }));}
    void SetMessageAllocatorFor_PredictRelation(
        ::grpc::MessageAllocator< ::protos::PredictRequest, ::protos::PredictResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::protos::PredictRequest, ::protos::PredictResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PredictRelation(
      ::grpc::CallbackServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PredictRelation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PredictRelation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PredictRelation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPredictRelation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PredictRelation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PredictRelation(context, request, response); }));
    }
    ~WithRawCallbackMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PredictRelation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PredictRelation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PredictRelation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::protos::PredictRequest, ::protos::PredictResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::protos::PredictRequest, ::protos::PredictResponse>* streamer) {
                       return this->StreamedPredictRelation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PredictRelation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PredictRelation(::grpc::ServerContext* /*context*/, const ::protos::PredictRequest* /*request*/, ::protos::PredictResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPredictRelation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::protos::PredictRequest,::protos::PredictResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PredictRelation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PredictRelation<Service > StreamedService;
};

}  // namespace protos


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_relation_2eproto__INCLUDED
